name: Pitest

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Pitest
        run: mvn test pitest:mutationCoverage
      - name: Upload Pitest to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pitest-mutation-testing
          path: target/pit-reports/**/*  
